### ISSUE TITLE
Issue adding association in the form

### ISSUE THREAD

**Issue by hallmatt** [dabroz/cocoon-js-vanilla#2]
Thanks for coming up with this! 

I have the gem installed, removed the old cocoon JS, added this package, along with the import line in my app.js. However, whenever I click the same cocoon link to add an association, I get the following error:

```javascript
Uncaught DOMException: Failed to execute 'insertAdjacentHTML' on 'Element': The value provided ('undefined') is not one of 'beforeBegin', 'afterBegin', 'beforeEnd', or 'afterEnd'.
```

Is there some additional set up step I'm missing?

Thanks!

**Comment by dabroz** [comment]
#3 should fix this.
